#!/usr/bin/env python

"""
List all variables in a TensorFlow checkpoint
"""

import argparse
from functools import reduce
from tensorflow.contrib.framework.python.framework import checkpoint_utils


def main():
    parser = argparse.ArgumentParser(description='List all variables in a TensorFlow checkpoint')
    parser.add_argument('filename')
    args = parser.parse_args()

    variables = checkpoint_utils.list_variables(args.filename)

    number_of_variables = 0

    for name, shape in variables:
        print('%s: %s'% (name, shape))
        if len(shape) > 0 and not 'Adam' in name:
            number_of_variables += reduce(lambda a, b: a*b, shape)

    print("Total number of network variables: {:,}".format(number_of_variables))
    print("This excludes variables with Adam in the name.")

if __name__ == '__main__':
    main()
